### ISSUE TITLE
takewhile should cons the failing predicate back to the iterable

### ISSUE THREAD

**Issue by Netherdrake** [Suor/funcy#58]
```
>>> foo = iter(range(5))
>>> list(takewhile(lambda x: x <=2, foo))
[0, 1, 2]
```

By this point, one would expect that the `foo` iterable would have `[3, 4]` left.
Instead, we get:
```
>>> list(foo)
[4]
```

This is because `3` is burned (consumed) by the `takewhile` predicate, and in case of False condition it is never returned to the original iterable.

**Comment by Suor** [comment]
There is no such thing as "push item back to iterator" in Python. Maybe
split_by() function will help you:

https://funcy.readthedocs.io/en/stable/seqs.html#isplit_by

3 дек. 2017 г. 6:22 пользователь "furion" <notifications@github.com>
написал:

>>> foo = iter(range(5))
>>> list(takewhile(lambda x: x <=2, foo))
[0, 1, 2]

By this point, one would expect that the foo iterable would have [3, 4]
left.
Instead, we get:

>>> list(foo)
[4]

This is because 3 is burned (consumed) by the takewhile predicate, and in
case of False condition, it is never returned to the original iterable.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Suor/funcy/issues/58>, or mute the thread

**Comment by Netherdrake** [comment]
`split_by` solves my problem perfectly.

For pushing in front of iterable, one could simply:
```
In [1]: def cons(x, it):
   ...:     yield x
   ...:     yield from it
   ...:

In [2]: list(cons(5, iter(range(10))))
Out[2]: [5, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
`

**Comment by Suor** [comment]
Your `cons()` creates new iterator with item added, to make `takewhile()` behave as you described one need to add item to existing iterator passed to function.
